let age = 14;
console.log(age);
let name = "Danulo";
console.log(name);
let isStudent = true;
console.log(isStudent);
let myString = "hello my name is Danulo";
console.log(myString);
let myNumber = 7;
console.log(myNumber + 10);
let myNull = null;
console.log(myNull);
const userName = prompt('Введіть своє ім’я');
alert(`${userName}`);
console.log(typeof userName);
let userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log(userAnswer);
alert("Увага! Дія може бути небезпечною.");
let txt = confirm("Ви впевнені, що хочете продовжити?");
